# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cyber_glove_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(653, 255)
        Dialog.setStyleSheet("background:white")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("QPushButton{border:none; font-size:16px;}\n"
"QPushButton:hover{font-weight:600; border-left:2px solid red;}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_connect = QtWidgets.QPushButton(self.widget)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButton_connect.setMaximumSize(QtCore.QSize(90, 16777215))
        self.pushButton_connect.setStyleSheet("")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 6, -1)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_f5_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f5_1.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f5_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f5_1.setObjectName("lineEdit_f5_1")
        self.gridLayout.addWidget(self.lineEdit_f5_1, 4, 2, 1, 1)
        self.lineEdit_f5_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f5_3.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f5_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f5_3.setObjectName("lineEdit_f5_3")
        self.gridLayout.addWidget(self.lineEdit_f5_3, 4, 4, 1, 1)
        self.lineEdit_f3_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f3_3.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f3_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f3_3.setObjectName("lineEdit_f3_3")
        self.gridLayout.addWidget(self.lineEdit_f3_3, 2, 4, 1, 1)
        self.lineEdit_f4_0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f4_0.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f4_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f4_0.setObjectName("lineEdit_f4_0")
        self.gridLayout.addWidget(self.lineEdit_f4_0, 3, 1, 1, 1)
        self.lineEdit_f2_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f2_3.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f2_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f2_3.setObjectName("lineEdit_f2_3")
        self.gridLayout.addWidget(self.lineEdit_f2_3, 1, 4, 1, 1)
        self.lineEdit_f4_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f4_2.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f4_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f4_2.setObjectName("lineEdit_f4_2")
        self.gridLayout.addWidget(self.lineEdit_f4_2, 3, 3, 1, 1)
        self.lineEdit_f3_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f3_1.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f3_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f3_1.setObjectName("lineEdit_f3_1")
        self.gridLayout.addWidget(self.lineEdit_f3_1, 2, 2, 1, 1)
        self.lineEdit_f3_0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f3_0.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f3_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f3_0.setObjectName("lineEdit_f3_0")
        self.gridLayout.addWidget(self.lineEdit_f3_0, 2, 1, 1, 1)
        self.lineEdit_f2_0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f2_0.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f2_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f2_0.setObjectName("lineEdit_f2_0")
        self.gridLayout.addWidget(self.lineEdit_f2_0, 1, 1, 1, 1)
        self.lineEdit_f4_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f4_3.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f4_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f4_3.setObjectName("lineEdit_f4_3")
        self.gridLayout.addWidget(self.lineEdit_f4_3, 3, 4, 1, 1)
        self.lineEdit_f3_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f3_2.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f3_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f3_2.setObjectName("lineEdit_f3_2")
        self.gridLayout.addWidget(self.lineEdit_f3_2, 2, 3, 1, 1)
        self.lineEdit_f5_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f5_2.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f5_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f5_2.setObjectName("lineEdit_f5_2")
        self.gridLayout.addWidget(self.lineEdit_f5_2, 4, 3, 1, 1)
        self.lineEdit_f5_0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f5_0.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f5_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f5_0.setObjectName("lineEdit_f5_0")
        self.gridLayout.addWidget(self.lineEdit_f5_0, 4, 1, 1, 1)
        self.lineEdit_f2_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f2_1.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f2_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f2_1.setObjectName("lineEdit_f2_1")
        self.gridLayout.addWidget(self.lineEdit_f2_1, 1, 2, 1, 1)
        self.lineEdit_f4_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f4_1.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f4_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f4_1.setObjectName("lineEdit_f4_1")
        self.gridLayout.addWidget(self.lineEdit_f4_1, 3, 2, 1, 1)
        self.lineEdit_f2_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f2_2.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f2_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f2_2.setObjectName("lineEdit_f2_2")
        self.gridLayout.addWidget(self.lineEdit_f2_2, 1, 3, 1, 1)
        self.lineEdit_f1_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f1_1.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f1_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f1_1.setObjectName("lineEdit_f1_1")
        self.gridLayout.addWidget(self.lineEdit_f1_1, 0, 2, 1, 1)
        self.lineEdit_f1_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f1_2.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f1_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f1_2.setObjectName("lineEdit_f1_2")
        self.gridLayout.addWidget(self.lineEdit_f1_2, 0, 3, 1, 1)
        self.lineEdit_f1_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f1_3.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f1_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f1_3.setObjectName("lineEdit_f1_3")
        self.gridLayout.addWidget(self.lineEdit_f1_3, 0, 4, 1, 1)
        self.lineEdit_f1_0 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_f1_0.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_f1_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_f1_0.setObjectName("lineEdit_f1_0")
        self.gridLayout.addWidget(self.lineEdit_f1_0, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 4, 1)
        self.pushButton_connect_to_rviz = QtWidgets.QPushButton(self.widget)
        self.pushButton_connect_to_rviz.setStyleSheet("")
        self.pushButton_connect_to_rviz.setObjectName("pushButton_connect_to_rviz")
        self.gridLayout_2.addWidget(self.pushButton_connect_to_rviz, 2, 0, 1, 1)
        self.pushButton_connect_to_gazebo = QtWidgets.QPushButton(self.widget)
        self.pushButton_connect_to_gazebo.setStyleSheet("")
        self.pushButton_connect_to_gazebo.setObjectName("pushButton_connect_to_gazebo")
        self.gridLayout_2.addWidget(self.pushButton_connect_to_gazebo, 3, 0, 1, 1)
        self.pushButton_get_data = QtWidgets.QPushButton(self.widget)
        self.pushButton_get_data.setObjectName("pushButton_get_data")
        self.gridLayout_2.addWidget(self.pushButton_get_data, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        self.pushButton_connect.clicked.connect(Dialog.connect)
        self.pushButton_connect_to_rviz.clicked.connect(Dialog.connect_to_rviz)
        self.pushButton_connect_to_gazebo.clicked.connect(Dialog.connect_to_gazebo)
        self.pushButton_get_data.clicked.connect(Dialog.get_data)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cyber Glove"))
        self.pushButton_connect.setText(_translate("Dialog", "connect"))
        self.lineEdit_f5_1.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f5_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f3_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f4_0.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f2_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f4_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f3_1.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f3_0.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f2_0.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f4_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f3_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f5_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f5_0.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f2_1.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f4_1.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f2_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f1_1.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f1_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f1_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_f1_0.setPlaceholderText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Thumb"))
        self.label_2.setText(_translate("Dialog", "Finger2"))
        self.label_3.setText(_translate("Dialog", "Finger3"))
        self.label_4.setText(_translate("Dialog", "Finger4"))
        self.label_5.setText(_translate("Dialog", "Finger5"))
        self.pushButton_connect_to_rviz.setText(_translate("Dialog", "connect \n"
"to rviz"))
        self.pushButton_connect_to_gazebo.setText(_translate("Dialog", "exec in\n"
"gazebo"))
        self.pushButton_get_data.setText(_translate("Dialog", "get data"))

