# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eigen_grasp.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(317, 331)
        Dialog.setStyleSheet("background:white")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 50, 211, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_jt_2_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_2_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_2_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_2_down.setDefault(False)
        self.pushButton_jt_2_down.setObjectName("pushButton_jt_2_down")
        self.gridLayout.addWidget(self.pushButton_jt_2_down, 3, 0, 1, 1)
        self.pushButton_jt_3_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_3_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_3_up.setToolTip("")
        self.pushButton_jt_3_up.setWhatsThis("")
        self.pushButton_jt_3_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_3_up.setCheckable(False)
        self.pushButton_jt_3_up.setObjectName("pushButton_jt_3_up")
        self.gridLayout.addWidget(self.pushButton_jt_3_up, 4, 2, 1, 1)
        self.pushButton_jt_b_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_b_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_b_up.setMaximumSize(QtCore.QSize(22, 16777215))
        self.pushButton_jt_b_up.setToolTip("")
        self.pushButton_jt_b_up.setWhatsThis("")
        self.pushButton_jt_b_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_b_up.setCheckable(False)
        self.pushButton_jt_b_up.setObjectName("pushButton_jt_b_up")
        self.gridLayout.addWidget(self.pushButton_jt_b_up, 0, 2, 1, 1)
        self.pushButton_jt_1_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_1_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_1_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_1_down.setDefault(False)
        self.pushButton_jt_1_down.setObjectName("pushButton_jt_1_down")
        self.gridLayout.addWidget(self.pushButton_jt_1_down, 2, 0, 1, 1)
        self.lineEdit_jt_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_1.setObjectName("lineEdit_jt_1")
        self.gridLayout.addWidget(self.lineEdit_jt_1, 2, 1, 1, 1)
        self.pushButton_jt_2_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_2_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_2_up.setToolTip("")
        self.pushButton_jt_2_up.setWhatsThis("")
        self.pushButton_jt_2_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_2_up.setCheckable(False)
        self.pushButton_jt_2_up.setObjectName("pushButton_jt_2_up")
        self.gridLayout.addWidget(self.pushButton_jt_2_up, 3, 2, 1, 1)
        self.pushButton_jt_3_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_3_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_3_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_3_down.setDefault(False)
        self.pushButton_jt_3_down.setObjectName("pushButton_jt_3_down")
        self.gridLayout.addWidget(self.pushButton_jt_3_down, 4, 0, 1, 1)
        self.pushButton_jt_0_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_0_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_0_up.setToolTip("")
        self.pushButton_jt_0_up.setWhatsThis("")
        self.pushButton_jt_0_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_0_up.setCheckable(False)
        self.pushButton_jt_0_up.setObjectName("pushButton_jt_0_up")
        self.gridLayout.addWidget(self.pushButton_jt_0_up, 1, 2, 1, 1)
        self.lineEdit_jt_b = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_b.setObjectName("lineEdit_jt_b")
        self.gridLayout.addWidget(self.lineEdit_jt_b, 0, 1, 1, 1)
        self.lineEdit_jt_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_2.setObjectName("lineEdit_jt_2")
        self.gridLayout.addWidget(self.lineEdit_jt_2, 3, 1, 1, 1)
        self.lineEdit_jt_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_3.setObjectName("lineEdit_jt_3")
        self.gridLayout.addWidget(self.lineEdit_jt_3, 4, 1, 1, 1)
        self.lineEdit_jt_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_0.setObjectName("lineEdit_jt_0")
        self.gridLayout.addWidget(self.lineEdit_jt_0, 1, 1, 1, 1)
        self.pushButton_jt_0_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_0_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_0_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_0_down.setDefault(False)
        self.pushButton_jt_0_down.setObjectName("pushButton_jt_0_down")
        self.gridLayout.addWidget(self.pushButton_jt_0_down, 1, 0, 1, 1)
        self.pushButton_jt_1_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_1_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_1_up.setToolTip("")
        self.pushButton_jt_1_up.setWhatsThis("")
        self.pushButton_jt_1_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_1_up.setCheckable(False)
        self.pushButton_jt_1_up.setObjectName("pushButton_jt_1_up")
        self.gridLayout.addWidget(self.pushButton_jt_1_up, 2, 2, 1, 1)
        self.pushButton_jt_b_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_b_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_b_down.setMaximumSize(QtCore.QSize(22, 16777215))
        self.pushButton_jt_b_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_b_down.setDefault(False)
        self.pushButton_jt_b_down.setObjectName("pushButton_jt_b_down")
        self.gridLayout.addWidget(self.pushButton_jt_b_down, 0, 0, 1, 1)
        self.lineEdit_delta_jtAngle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_delta_jtAngle.setGeometry(QtCore.QRect(85, 20, 60, 22))
        self.lineEdit_delta_jtAngle.setStyleSheet("border:1px solid gray")
        self.lineEdit_delta_jtAngle.setObjectName("lineEdit_delta_jtAngle")
        self.pushButton_set = QtWidgets.QPushButton(Dialog)
        self.pushButton_set.setGeometry(QtCore.QRect(210, 20, 80, 22))
        self.pushButton_set.setStyleSheet("")
        self.pushButton_set.setObjectName("pushButton_set")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 60, 33, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_jt_2_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_3_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_b_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_1_down.setText(_translate("Dialog", "-"))
        self.lineEdit_jt_1.setPlaceholderText(_translate("Dialog", "0"))
        self.pushButton_jt_2_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_3_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_0_up.setText(_translate("Dialog", "+"))
        self.lineEdit_jt_b.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_jt_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_jt_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_jt_0.setPlaceholderText(_translate("Dialog", "0"))
        self.pushButton_jt_0_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_1_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_b_down.setText(_translate("Dialog", "-"))
        self.lineEdit_delta_jtAngle.setPlaceholderText(_translate("Dialog", "1"))
        self.pushButton_set.setText(_translate("Dialog", "Set"))
        self.label.setText(_translate("Dialog", "PC1"))
        self.label_2.setText(_translate("Dialog", "PC2"))
        self.label_3.setText(_translate("Dialog", "PC3"))
        self.label_4.setText(_translate("Dialog", "PC4"))
        self.label_5.setText(_translate("Dialog", "PC5"))

