# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hand_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 589)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contact_widget = QtWidgets.QWidget(self.centralwidget)
        self.contact_widget.setObjectName("contact_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contact_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.contact_widget)
        self.label_2.setStyleSheet("font: 15pt \'\'sans serif\'\'")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_set_zero = QtWidgets.QPushButton(self.contact_widget)
        self.pushButton_set_zero.setObjectName("pushButton_set_zero")
        self.horizontalLayout_5.addWidget(self.pushButton_set_zero)
        self.pushButton_teach = QtWidgets.QPushButton(self.contact_widget)
        self.pushButton_teach.setObjectName("pushButton_teach")
        self.horizontalLayout_5.addWidget(self.pushButton_teach)
        self.comboBox_contact = QtWidgets.QComboBox(self.contact_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_contact.sizePolicy().hasHeightForWidth())
        self.comboBox_contact.setSizePolicy(sizePolicy)
        self.comboBox_contact.setMinimumSize(QtCore.QSize(80, 20))
        self.comboBox_contact.setObjectName("comboBox_contact")
        self.comboBox_contact.addItem("")
        self.comboBox_contact.addItem("")
        self.comboBox_contact.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_contact)
        self.textEdit_contact = QtWidgets.QTextEdit(self.contact_widget)
        self.textEdit_contact.setMinimumSize(QtCore.QSize(500, 0))
        self.textEdit_contact.setObjectName("textEdit_contact")
        self.horizontalLayout_5.addWidget(self.textEdit_contact)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.contact_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setEnabled(True)
        self.label_47.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 1, 2, 1, 1)
        self.lineEdit_jt_f1_3_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_3_t.setReadOnly(True)
        self.lineEdit_jt_f1_3_t.setObjectName("lineEdit_jt_f1_3_t")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_3_t, 6, 1, 1, 1)
        self.lineEdit_jt_f1_1_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_1_c.setReadOnly(True)
        self.lineEdit_jt_f1_1_c.setObjectName("lineEdit_jt_f1_1_c")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_1_c, 4, 2, 1, 1)
        self.lineEdit_jt_f1_3_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_3_c.setReadOnly(True)
        self.lineEdit_jt_f1_3_c.setObjectName("lineEdit_jt_f1_3_c")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_3_c, 6, 2, 1, 1)
        self.lineEdit_jt_f1_1_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_1_t.setReadOnly(True)
        self.lineEdit_jt_f1_1_t.setObjectName("lineEdit_jt_f1_1_t")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_1_t, 4, 1, 1, 1)
        self.lineEdit_jt_f1_b_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_b_t.setReadOnly(True)
        self.lineEdit_jt_f1_b_t.setObjectName("lineEdit_jt_f1_b_t")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_b_t, 2, 1, 1, 1)
        self.lineEdit_jt_f1_2_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_2_t.setReadOnly(True)
        self.lineEdit_jt_f1_2_t.setObjectName("lineEdit_jt_f1_2_t")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_2_t, 5, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 1, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 1, 0, 1, 1)
        self.lineEdit_jt_f1_0_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_0_c.setReadOnly(True)
        self.lineEdit_jt_f1_0_c.setObjectName("lineEdit_jt_f1_0_c")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_0_c, 3, 2, 1, 1)
        self.lineEdit_jt_f1_b_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_b_c.setEnabled(True)
        self.lineEdit_jt_f1_b_c.setReadOnly(True)
        self.lineEdit_jt_f1_b_c.setObjectName("lineEdit_jt_f1_b_c")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_b_c, 2, 2, 1, 1)
        self.lineEdit_jt_f1_2_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_2_c.setReadOnly(True)
        self.lineEdit_jt_f1_2_c.setObjectName("lineEdit_jt_f1_2_c")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_2_c, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_3.setStyleSheet("\n"
"font: 16pt \"Sans Serif\";font-weight:700;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 3)
        self.lineEdit_jt_f1_b_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_b_p.setReadOnly(True)
        self.lineEdit_jt_f1_b_p.setObjectName("lineEdit_jt_f1_b_p")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_b_p, 2, 0, 1, 1)
        self.lineEdit_jt_f1_0_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_0_t.setReadOnly(True)
        self.lineEdit_jt_f1_0_t.setObjectName("lineEdit_jt_f1_0_t")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_0_t, 3, 1, 1, 1)
        self.lineEdit_jt_f1_0_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_0_p.setReadOnly(True)
        self.lineEdit_jt_f1_0_p.setObjectName("lineEdit_jt_f1_0_p")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_0_p, 3, 0, 1, 1)
        self.lineEdit_jt_f1_1_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_1_p.setReadOnly(True)
        self.lineEdit_jt_f1_1_p.setObjectName("lineEdit_jt_f1_1_p")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_1_p, 4, 0, 1, 1)
        self.lineEdit_jt_f1_2_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_2_p.setReadOnly(True)
        self.lineEdit_jt_f1_2_p.setObjectName("lineEdit_jt_f1_2_p")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_2_p, 5, 0, 1, 1)
        self.lineEdit_jt_f1_3_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f1_3_p.setReadOnly(True)
        self.lineEdit_jt_f1_3_p.setObjectName("lineEdit_jt_f1_3_p")
        self.gridLayout_8.addWidget(self.lineEdit_jt_f1_3_p, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_8)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setMaximumSize(QtCore.QSize(10, 16777215))
        self.lineEdit.setStyleSheet("border:none")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_jt_f2_1_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_1_c.setReadOnly(True)
        self.lineEdit_jt_f2_1_c.setObjectName("lineEdit_jt_f2_1_c")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_1_c, 4, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_9.addWidget(self.label_49, 1, 1, 1, 1)
        self.lineEdit_jt_f2_3_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_3_c.setReadOnly(True)
        self.lineEdit_jt_f2_3_c.setObjectName("lineEdit_jt_f2_3_c")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_3_c, 6, 2, 1, 1)
        self.lineEdit_jt_f2_3_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_3_p.setReadOnly(True)
        self.lineEdit_jt_f2_3_p.setObjectName("lineEdit_jt_f2_3_p")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_3_p, 6, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.gridLayout_9.addWidget(self.label_50, 1, 0, 1, 1)
        self.lineEdit_jt_f2_0_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_0_c.setReadOnly(True)
        self.lineEdit_jt_f2_0_c.setObjectName("lineEdit_jt_f2_0_c")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_0_c, 3, 2, 1, 1)
        self.lineEdit_jt_f2_b_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_b_c.setEnabled(True)
        self.lineEdit_jt_f2_b_c.setReadOnly(True)
        self.lineEdit_jt_f2_b_c.setObjectName("lineEdit_jt_f2_b_c")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_b_c, 2, 2, 1, 1)
        self.lineEdit_jt_f2_2_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_2_c.setReadOnly(True)
        self.lineEdit_jt_f2_2_c.setObjectName("lineEdit_jt_f2_2_c")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_2_c, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setStyleSheet("\n"
"font: 16pt \"Sans Serif\";font-weight:700;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 3)
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setEnabled(True)
        self.label_48.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 1, 2, 1, 1)
        self.lineEdit_jt_f2_1_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_1_p.setReadOnly(True)
        self.lineEdit_jt_f2_1_p.setObjectName("lineEdit_jt_f2_1_p")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_1_p, 4, 0, 1, 1)
        self.lineEdit_jt_f2_0_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_0_p.setReadOnly(True)
        self.lineEdit_jt_f2_0_p.setObjectName("lineEdit_jt_f2_0_p")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_0_p, 3, 0, 1, 1)
        self.lineEdit_jt_f2_0_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_0_t.setReadOnly(True)
        self.lineEdit_jt_f2_0_t.setObjectName("lineEdit_jt_f2_0_t")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_0_t, 3, 1, 1, 1)
        self.lineEdit_jt_f2_3_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_3_t.setReadOnly(True)
        self.lineEdit_jt_f2_3_t.setObjectName("lineEdit_jt_f2_3_t")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_3_t, 6, 1, 1, 1)
        self.lineEdit_jt_f2_2_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_2_t.setReadOnly(True)
        self.lineEdit_jt_f2_2_t.setObjectName("lineEdit_jt_f2_2_t")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_2_t, 5, 1, 1, 1)
        self.lineEdit_jt_f2_1_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_1_t.setReadOnly(True)
        self.lineEdit_jt_f2_1_t.setObjectName("lineEdit_jt_f2_1_t")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_1_t, 4, 1, 1, 1)
        self.lineEdit_jt_f2_b_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_b_p.setReadOnly(True)
        self.lineEdit_jt_f2_b_p.setObjectName("lineEdit_jt_f2_b_p")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_b_p, 2, 0, 1, 1)
        self.lineEdit_jt_f2_b_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_b_t.setReadOnly(True)
        self.lineEdit_jt_f2_b_t.setObjectName("lineEdit_jt_f2_b_t")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_b_t, 2, 1, 1, 1)
        self.lineEdit_jt_f2_2_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f2_2_p.setReadOnly(True)
        self.lineEdit_jt_f2_2_p.setObjectName("lineEdit_jt_f2_2_p")
        self.gridLayout_9.addWidget(self.lineEdit_jt_f2_2_p, 5, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.lineEdit_2.setStyleSheet("border:none")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_jt_f3_1_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_1_c.setReadOnly(True)
        self.lineEdit_jt_f3_1_c.setObjectName("lineEdit_jt_f3_1_c")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_1_c, 4, 2, 1, 1)
        self.lineEdit_jt_f3_2_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_2_p.setReadOnly(True)
        self.lineEdit_jt_f3_2_p.setObjectName("lineEdit_jt_f3_2_p")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_2_p, 5, 0, 1, 1)
        self.lineEdit_jt_f3_3_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_3_c.setReadOnly(True)
        self.lineEdit_jt_f3_3_c.setObjectName("lineEdit_jt_f3_3_c")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_3_c, 6, 2, 1, 1)
        self.lineEdit_jt_f3_1_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_1_p.setReadOnly(True)
        self.lineEdit_jt_f3_1_p.setObjectName("lineEdit_jt_f3_1_p")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_1_p, 4, 0, 1, 1)
        self.lineEdit_jt_f3_1_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_1_t.setReadOnly(True)
        self.lineEdit_jt_f3_1_t.setObjectName("lineEdit_jt_f3_1_t")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_1_t, 4, 1, 1, 1)
        self.lineEdit_jt_f3_b_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_b_t.setReadOnly(True)
        self.lineEdit_jt_f3_b_t.setObjectName("lineEdit_jt_f3_b_t")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_b_t, 2, 1, 1, 1)
        self.lineEdit_jt_f3_2_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_2_t.setReadOnly(True)
        self.lineEdit_jt_f3_2_t.setObjectName("lineEdit_jt_f3_2_t")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_2_t, 5, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 1, 1, 1, 1)
        self.lineEdit_jt_f3_b_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_b_p.setReadOnly(True)
        self.lineEdit_jt_f3_b_p.setObjectName("lineEdit_jt_f3_b_p")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_b_p, 2, 0, 1, 1)
        self.lineEdit_jt_f3_0_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_0_p.setReadOnly(True)
        self.lineEdit_jt_f3_0_p.setObjectName("lineEdit_jt_f3_0_p")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_0_p, 3, 0, 1, 1)
        self.lineEdit_jt_f3_0_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_0_t.setReadOnly(True)
        self.lineEdit_jt_f3_0_t.setObjectName("lineEdit_jt_f3_0_t")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_0_t, 3, 1, 1, 1)
        self.lineEdit_jt_f3_3_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_3_p.setReadOnly(True)
        self.lineEdit_jt_f3_3_p.setObjectName("lineEdit_jt_f3_3_p")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_3_p, 6, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_10.addWidget(self.label_53, 1, 0, 1, 1)
        self.lineEdit_jt_f3_0_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_0_c.setReadOnly(True)
        self.lineEdit_jt_f3_0_c.setObjectName("lineEdit_jt_f3_0_c")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_0_c, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setStyleSheet("\n"
"font: 16pt \"Sans Serif\";font-weight:700;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 3)
        self.lineEdit_jt_f3_b_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_b_c.setEnabled(True)
        self.lineEdit_jt_f3_b_c.setReadOnly(True)
        self.lineEdit_jt_f3_b_c.setObjectName("lineEdit_jt_f3_b_c")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_b_c, 2, 2, 1, 1)
        self.lineEdit_jt_f3_2_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_2_c.setReadOnly(True)
        self.lineEdit_jt_f3_2_c.setObjectName("lineEdit_jt_f3_2_c")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_2_c, 5, 2, 1, 1)
        self.lineEdit_jt_f3_3_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f3_3_t.setReadOnly(True)
        self.lineEdit_jt_f3_3_t.setObjectName("lineEdit_jt_f3_3_t")
        self.gridLayout_10.addWidget(self.lineEdit_jt_f3_3_t, 6, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setEnabled(True)
        self.label_51.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.gridLayout_10.addWidget(self.label_51, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_10)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(10, 16777215))
        self.lineEdit_3.setStyleSheet("border:none")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setEnabled(True)
        self.label_54.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.gridLayout_11.addWidget(self.label_54, 1, 2, 1, 1)
        self.lineEdit_jt_f4_3_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_3_t.setReadOnly(True)
        self.lineEdit_jt_f4_3_t.setObjectName("lineEdit_jt_f4_3_t")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_3_t, 6, 1, 1, 1)
        self.lineEdit_jt_f4_1_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_1_c.setReadOnly(True)
        self.lineEdit_jt_f4_1_c.setObjectName("lineEdit_jt_f4_1_c")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_1_c, 4, 2, 1, 1)
        self.lineEdit_jt_f4_2_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_2_p.setReadOnly(True)
        self.lineEdit_jt_f4_2_p.setObjectName("lineEdit_jt_f4_2_p")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_2_p, 5, 0, 1, 1)
        self.lineEdit_jt_f4_3_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_3_c.setReadOnly(True)
        self.lineEdit_jt_f4_3_c.setObjectName("lineEdit_jt_f4_3_c")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_3_c, 6, 2, 1, 1)
        self.lineEdit_jt_f4_1_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_1_p.setReadOnly(True)
        self.lineEdit_jt_f4_1_p.setObjectName("lineEdit_jt_f4_1_p")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_1_p, 4, 0, 1, 1)
        self.lineEdit_jt_f4_1_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_1_t.setReadOnly(True)
        self.lineEdit_jt_f4_1_t.setObjectName("lineEdit_jt_f4_1_t")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_1_t, 4, 1, 1, 1)
        self.lineEdit_jt_f4_b_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_b_t.setReadOnly(True)
        self.lineEdit_jt_f4_b_t.setObjectName("lineEdit_jt_f4_b_t")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_b_t, 2, 1, 1, 1)
        self.lineEdit_jt_f4_2_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_2_t.setReadOnly(True)
        self.lineEdit_jt_f4_2_t.setObjectName("lineEdit_jt_f4_2_t")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_2_t, 5, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 1, 1, 1, 1)
        self.lineEdit_jt_f4_b_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_b_p.setReadOnly(True)
        self.lineEdit_jt_f4_b_p.setObjectName("lineEdit_jt_f4_b_p")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_b_p, 2, 0, 1, 1)
        self.lineEdit_jt_f4_0_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_0_p.setReadOnly(True)
        self.lineEdit_jt_f4_0_p.setObjectName("lineEdit_jt_f4_0_p")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_0_p, 3, 0, 1, 1)
        self.lineEdit_jt_f4_0_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_0_t.setReadOnly(True)
        self.lineEdit_jt_f4_0_t.setObjectName("lineEdit_jt_f4_0_t")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_0_t, 3, 1, 1, 1)
        self.lineEdit_jt_f4_3_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_3_p.setReadOnly(True)
        self.lineEdit_jt_f4_3_p.setObjectName("lineEdit_jt_f4_3_p")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_3_p, 6, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 1, 0, 1, 1)
        self.lineEdit_jt_f4_0_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_0_c.setReadOnly(True)
        self.lineEdit_jt_f4_0_c.setObjectName("lineEdit_jt_f4_0_c")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_0_c, 3, 2, 1, 1)
        self.lineEdit_jt_f4_b_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_b_c.setEnabled(True)
        self.lineEdit_jt_f4_b_c.setReadOnly(True)
        self.lineEdit_jt_f4_b_c.setObjectName("lineEdit_jt_f4_b_c")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_b_c, 2, 2, 1, 1)
        self.lineEdit_jt_f4_2_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f4_2_c.setReadOnly(True)
        self.lineEdit_jt_f4_2_c.setObjectName("lineEdit_jt_f4_2_c")
        self.gridLayout_11.addWidget(self.lineEdit_jt_f4_2_c, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setStyleSheet("\n"
"font: 16pt \"Sans Serif\";font-weight:700;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setEnabled(False)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(10, 16777215))
        self.lineEdit_4.setStyleSheet("border:none")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setEnabled(True)
        self.label_57.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_12.addWidget(self.label_57, 1, 2, 1, 1)
        self.lineEdit_jt_f5_3_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_3_t.setReadOnly(True)
        self.lineEdit_jt_f5_3_t.setObjectName("lineEdit_jt_f5_3_t")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_3_t, 6, 1, 1, 1)
        self.lineEdit_jt_f5_1_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_1_c.setReadOnly(True)
        self.lineEdit_jt_f5_1_c.setObjectName("lineEdit_jt_f5_1_c")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_1_c, 4, 2, 1, 1)
        self.lineEdit_jt_f5_2_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_2_p.setReadOnly(True)
        self.lineEdit_jt_f5_2_p.setObjectName("lineEdit_jt_f5_2_p")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_2_p, 5, 0, 1, 1)
        self.lineEdit_jt_f5_3_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_3_c.setReadOnly(True)
        self.lineEdit_jt_f5_3_c.setObjectName("lineEdit_jt_f5_3_c")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_3_c, 6, 2, 1, 1)
        self.lineEdit_jt_f5_1_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_1_p.setReadOnly(True)
        self.lineEdit_jt_f5_1_p.setObjectName("lineEdit_jt_f5_1_p")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_1_p, 4, 0, 1, 1)
        self.lineEdit_jt_f5_1_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_1_t.setReadOnly(True)
        self.lineEdit_jt_f5_1_t.setObjectName("lineEdit_jt_f5_1_t")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_1_t, 4, 1, 1, 1)
        self.lineEdit_jt_f5_b_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_b_t.setReadOnly(True)
        self.lineEdit_jt_f5_b_t.setObjectName("lineEdit_jt_f5_b_t")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_b_t, 2, 1, 1, 1)
        self.lineEdit_jt_f5_2_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_2_t.setReadOnly(True)
        self.lineEdit_jt_f5_2_t.setObjectName("lineEdit_jt_f5_2_t")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_2_t, 5, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_12.addWidget(self.label_58, 1, 1, 1, 1)
        self.lineEdit_jt_f5_b_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_b_p.setReadOnly(True)
        self.lineEdit_jt_f5_b_p.setObjectName("lineEdit_jt_f5_b_p")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_b_p, 2, 0, 1, 1)
        self.lineEdit_jt_f5_0_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_0_p.setReadOnly(True)
        self.lineEdit_jt_f5_0_p.setObjectName("lineEdit_jt_f5_0_p")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_0_p, 3, 0, 1, 1)
        self.lineEdit_jt_f5_0_t = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_0_t.setReadOnly(True)
        self.lineEdit_jt_f5_0_t.setObjectName("lineEdit_jt_f5_0_t")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_0_t, 3, 1, 1, 1)
        self.lineEdit_jt_f5_3_p = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_3_p.setReadOnly(True)
        self.lineEdit_jt_f5_3_p.setObjectName("lineEdit_jt_f5_3_p")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_3_p, 6, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_12.addWidget(self.label_59, 1, 0, 1, 1)
        self.lineEdit_jt_f5_0_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_0_c.setReadOnly(True)
        self.lineEdit_jt_f5_0_c.setObjectName("lineEdit_jt_f5_0_c")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_0_c, 3, 2, 1, 1)
        self.lineEdit_jt_f5_b_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_b_c.setEnabled(True)
        self.lineEdit_jt_f5_b_c.setReadOnly(True)
        self.lineEdit_jt_f5_b_c.setObjectName("lineEdit_jt_f5_b_c")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_b_c, 2, 2, 1, 1)
        self.lineEdit_jt_f5_2_c = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jt_f5_2_c.setReadOnly(True)
        self.lineEdit_jt_f5_2_c.setObjectName("lineEdit_jt_f5_2_c")
        self.gridLayout_12.addWidget(self.lineEdit_jt_f5_2_c, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setStyleSheet("\n"
"font: 16pt \"Sans Serif\";font-weight:700;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_12.addWidget(self.label_7, 0, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout_12)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 19))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Grasp = QtWidgets.QMenu(self.menubar)
        self.menu_Grasp.setObjectName("menu_Grasp")
        self.menu_Arm = QtWidgets.QMenu(self.menubar)
        self.menu_Arm.setObjectName("menu_Arm")
        self.menu_Measure = QtWidgets.QMenu(self.menubar)
        self.menu_Measure.setObjectName("menu_Measure")
        self.menu_Data_Glove = QtWidgets.QMenu(self.menubar)
        self.menu_Data_Glove.setObjectName("menu_Data_Glove")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_angle = QtWidgets.QAction(MainWindow)
        self.actionSet_angle.setObjectName("actionSet_angle")
        self.actionEigen_Grasp = QtWidgets.QAction(MainWindow)
        self.actionEigen_Grasp.setObjectName("actionEigen_Grasp")
        self.actionIdentity_Grasp = QtWidgets.QAction(MainWindow)
        self.actionIdentity_Grasp.setObjectName("actionIdentity_Grasp")
        self.actionDecarte_Plan = QtWidgets.QAction(MainWindow)
        self.actionDecarte_Plan.setObjectName("actionDecarte_Plan")
        self.actionJoint_Plan = QtWidgets.QAction(MainWindow)
        self.actionJoint_Plan.setObjectName("actionJoint_Plan")
        self.actionLoad_or_Save_Grasp = QtWidgets.QAction(MainWindow)
        self.actionLoad_or_Save_Grasp.setObjectName("actionLoad_or_Save_Grasp")
        self.actionCal_Metric = QtWidgets.QAction(MainWindow)
        self.actionCal_Metric.setObjectName("actionCal_Metric")
        self.actionOpenGlove = QtWidgets.QAction(MainWindow)
        self.actionOpenGlove.setObjectName("actionOpenGlove")
        self.actionLoadandSave = QtWidgets.QAction(MainWindow)
        self.actionLoadandSave.setObjectName("actionLoadandSave")
        self.actionPrincipalComponents = QtWidgets.QAction(MainWindow)
        self.actionPrincipalComponents.setObjectName("actionPrincipalComponents")
        self.menu_Grasp.addAction(self.actionEigen_Grasp)
        self.menu_Grasp.addAction(self.actionIdentity_Grasp)
        self.menu_Grasp.addAction(self.actionLoadandSave)
        self.menu_Grasp.addAction(self.actionPrincipalComponents)
        self.menu_Arm.addAction(self.actionDecarte_Plan)
        self.menu_Arm.addAction(self.actionJoint_Plan)
        self.menu_Measure.addAction(self.actionCal_Metric)
        self.menu_Data_Glove.addAction(self.actionOpenGlove)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Grasp.menuAction())
        self.menubar.addAction(self.menu_Arm.menuAction())
        self.menubar.addAction(self.menu_Measure.menuAction())
        self.menubar.addAction(self.menu_Data_Glove.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_contact.activated['QString'].connect(MainWindow.showContact)
        self.actionIdentity_Grasp.triggered.connect(MainWindow.show_Identity_grasp_window)
        self.actionJoint_Plan.triggered.connect(MainWindow.show_arm_joint_plan_window)
        self.actionDecarte_Plan.triggered.connect(MainWindow.show_arm_end_plan_window)
        self.actionOpenGlove.triggered.connect(MainWindow.show_cyberglove)
        self.actionLoadandSave.triggered.connect(MainWindow.show_load_save)
        self.actionCal_Metric.triggered.connect(MainWindow.show_quality_measure)
        self.actionEigen_Grasp.triggered.connect(MainWindow.show_eigen_grasp)
        self.pushButton_teach.clicked.connect(MainWindow.move_by_teach)
        self.pushButton_set_zero.clicked.connect(MainWindow.set_all_zero)
        self.actionPrincipalComponents.triggered.connect(MainWindow.show_PCslider)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Contacts"))
        self.pushButton_set_zero.setText(_translate("MainWindow", "set zero"))
        self.pushButton_teach.setText(_translate("MainWindow", "teach"))
        self.comboBox_contact.setItemText(0, _translate("MainWindow", "Finger1"))
        self.comboBox_contact.setItemText(1, _translate("MainWindow", "Finger2"))
        self.comboBox_contact.setItemText(2, _translate("MainWindow", "Finger3"))
        self.label_47.setText(_translate("MainWindow", "contact"))
        self.lineEdit_jt_f1_1_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f1_3_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f1_b_t.setText(_translate("MainWindow", "None"))
        self.label_46.setText(_translate("MainWindow", "torque"))
        self.label_45.setText(_translate("MainWindow", "angle"))
        self.lineEdit_jt_f1_0_c.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f1_b_c.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f1_2_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "F1"))
        self.lineEdit_jt_f1_b_p.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f1_0_t.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f1_0_p.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f2_1_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_49.setText(_translate("MainWindow", "torque"))
        self.lineEdit_jt_f2_3_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_50.setText(_translate("MainWindow", "angle"))
        self.lineEdit_jt_f2_0_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f2_b_c.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f2_2_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "F2"))
        self.label_48.setText(_translate("MainWindow", "contact"))
        self.lineEdit_jt_f2_b_p.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f2_b_t.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f3_1_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f3_3_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f3_b_t.setText(_translate("MainWindow", "None"))
        self.label_52.setText(_translate("MainWindow", "torque"))
        self.lineEdit_jt_f3_b_p.setText(_translate("MainWindow", "None"))
        self.label_53.setText(_translate("MainWindow", "angle"))
        self.lineEdit_jt_f3_0_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "F3"))
        self.lineEdit_jt_f3_b_c.setText(_translate("MainWindow", "None"))
        self.lineEdit_jt_f3_2_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_51.setText(_translate("MainWindow", "contact"))
        self.label_54.setText(_translate("MainWindow", "contact"))
        self.lineEdit_jt_f4_1_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f4_3_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_55.setText(_translate("MainWindow", "torque"))
        self.label_56.setText(_translate("MainWindow", "angle"))
        self.lineEdit_jt_f4_0_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f4_b_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f4_2_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "F4"))
        self.label_57.setText(_translate("MainWindow", "contact"))
        self.lineEdit_jt_f5_1_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f5_3_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "torque"))
        self.label_59.setText(_translate("MainWindow", "angle"))
        self.lineEdit_jt_f5_0_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f5_b_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.lineEdit_jt_f5_2_c.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "F5"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Grasp.setTitle(_translate("MainWindow", "&Grasp"))
        self.menu_Arm.setTitle(_translate("MainWindow", "&Arm"))
        self.menu_Measure.setTitle(_translate("MainWindow", "&Measure"))
        self.menu_Data_Glove.setTitle(_translate("MainWindow", "&Data Glove"))
        self.actionSet_angle.setText(_translate("MainWindow", "Set angle"))
        self.actionEigen_Grasp.setText(_translate("MainWindow", "Eigen Grasp"))
        self.actionIdentity_Grasp.setText(_translate("MainWindow", "Identity Grasp"))
        self.actionDecarte_Plan.setText(_translate("MainWindow", "Decarte Plan"))
        self.actionJoint_Plan.setText(_translate("MainWindow", "Joint Plan"))
        self.actionLoad_or_Save_Grasp.setText(_translate("MainWindow", "Load or Save Grasp"))
        self.actionCal_Metric.setText(_translate("MainWindow", "Cal Metric"))
        self.actionOpenGlove.setText(_translate("MainWindow", "OpenGlove"))
        self.actionLoadandSave.setText(_translate("MainWindow", "LoadandSave"))
        self.actionPrincipalComponents.setText(_translate("MainWindow", "PrincipalComponents"))

