# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quality_cal_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(617, 303)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background:white")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(18, 18, 18, 18)
        self.gridLayout_2.setSpacing(18)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_norm = QtWidgets.QComboBox(self.widget)
        self.comboBox_norm.setStyleSheet("border:1pt solid gray")
        self.comboBox_norm.setObjectName("comboBox_norm")
        self.comboBox_norm.addItem("")
        self.comboBox_norm.addItem("")
        self.gridLayout.addWidget(self.comboBox_norm, 1, 1, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.widget)
        self.comboBox_type.setStyleSheet("border:1pt solid gray")
        self.comboBox_type.setObjectName("comboBox_type")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.gridLayout.addWidget(self.comboBox_type, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("QLabel{font-size:14px;}")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("QLabel{font-size:14px;}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("QLabel{font-size:14px;}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_quality = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_quality.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_quality.setStyleSheet("QLable{border:2px solid black;width:300px;}")
        self.lineEdit_quality.setObjectName("lineEdit_quality")
        self.gridLayout.addWidget(self.lineEdit_quality, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_read = QtWidgets.QPushButton(self.widget)
        self.pushButton_read.setStyleSheet("")
        self.pushButton_read.setObjectName("pushButton_read")
        self.horizontalLayout_2.addWidget(self.pushButton_read)
        self.pushButton_save = QtWidgets.QPushButton(self.widget)
        self.pushButton_save.setStyleSheet("")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_2.addWidget(self.pushButton_save)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("QLabel{font-size:14px;font-weight:700}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit_contacts = QtWidgets.QTextEdit(self.widget)
        self.textEdit_contacts.setStyleSheet("border:2px solid gray;")
        self.textEdit_contacts.setObjectName("textEdit_contacts")
        self.verticalLayout.addWidget(self.textEdit_contacts)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.pushButton_cal = QtWidgets.QPushButton(self.widget)
        self.pushButton_cal.setStyleSheet("")
        self.pushButton_cal.setObjectName("pushButton_cal")
        self.gridLayout_2.addWidget(self.pushButton_cal, 1, 1, 1, 2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(Dialog)
        self.pushButton_cal.clicked.connect(Dialog.calculate)
        self.pushButton_read.clicked.connect(Dialog.read)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "quality_cal"))
        self.comboBox_norm.setItemText(0, _translate("Dialog", "L1 Norm"))
        self.comboBox_norm.setItemText(1, _translate("Dialog", "L Infinity Norm"))
        self.comboBox_type.setItemText(0, _translate("Dialog", "Epsilon"))
        self.comboBox_type.setItemText(1, _translate("Dialog", "Volume"))
        self.label_3.setText(_translate("Dialog", "Limit unit GWS using:"))
        self.label_4.setText(_translate("Dialog", "Calculate Quality"))
        self.label_2.setText(_translate("Dialog", "Quality Measure Type"))
        self.lineEdit_quality.setPlaceholderText(_translate("Dialog", "0"))
        self.pushButton_read.setText(_translate("Dialog", "read"))
        self.pushButton_save.setText(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "Contacts Info"))
        self.pushButton_cal.setText(_translate("Dialog", "Calculate"))

