# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zhangqb/catkin_ws/src/gazebo_tutorials/scripts/hand_show/ui/Identity.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 365)
        Dialog.setStyleSheet("background:white")
        self.pushButton_set = QtWidgets.QPushButton(Dialog)
        self.pushButton_set.setGeometry(QtCore.QRect(205, 30, 80, 22))
        self.pushButton_set.setStyleSheet("")
        self.pushButton_set.setObjectName("pushButton_set")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(55, 70, 211, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_jt_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_1.setObjectName("lineEdit_jt_1")
        self.gridLayout.addWidget(self.lineEdit_jt_1, 2, 1, 1, 1)
        self.pushButton_jt_0_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_0_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_0_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_0_down.setDefault(False)
        self.pushButton_jt_0_down.setObjectName("pushButton_jt_0_down")
        self.gridLayout.addWidget(self.pushButton_jt_0_down, 1, 0, 1, 1)
        self.pushButton_jt_b_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_b_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_b_down.setMaximumSize(QtCore.QSize(22, 16777215))
        self.pushButton_jt_b_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_b_down.setDefault(False)
        self.pushButton_jt_b_down.setObjectName("pushButton_jt_b_down")
        self.gridLayout.addWidget(self.pushButton_jt_b_down, 0, 0, 1, 1)
        self.pushButton_jt_3_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_3_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_3_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_3_down.setDefault(False)
        self.pushButton_jt_3_down.setObjectName("pushButton_jt_3_down")
        self.gridLayout.addWidget(self.pushButton_jt_3_down, 4, 0, 1, 1)
        self.pushButton_jt_1_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_1_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_1_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_1_down.setDefault(False)
        self.pushButton_jt_1_down.setObjectName("pushButton_jt_1_down")
        self.gridLayout.addWidget(self.pushButton_jt_1_down, 2, 0, 1, 1)
        self.pushButton_jt_0_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_0_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_0_up.setToolTip("")
        self.pushButton_jt_0_up.setWhatsThis("")
        self.pushButton_jt_0_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_0_up.setCheckable(False)
        self.pushButton_jt_0_up.setObjectName("pushButton_jt_0_up")
        self.gridLayout.addWidget(self.pushButton_jt_0_up, 1, 2, 1, 1)
        self.pushButton_jt_3_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_3_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_3_up.setToolTip("")
        self.pushButton_jt_3_up.setWhatsThis("")
        self.pushButton_jt_3_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_3_up.setCheckable(False)
        self.pushButton_jt_3_up.setObjectName("pushButton_jt_3_up")
        self.gridLayout.addWidget(self.pushButton_jt_3_up, 4, 2, 1, 1)
        self.pushButton_jt_2_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_2_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_2_up.setToolTip("")
        self.pushButton_jt_2_up.setWhatsThis("")
        self.pushButton_jt_2_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_2_up.setCheckable(False)
        self.pushButton_jt_2_up.setObjectName("pushButton_jt_2_up")
        self.gridLayout.addWidget(self.pushButton_jt_2_up, 3, 2, 1, 1)
        self.pushButton_jt_1_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_1_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_1_up.setToolTip("")
        self.pushButton_jt_1_up.setWhatsThis("")
        self.pushButton_jt_1_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_1_up.setCheckable(False)
        self.pushButton_jt_1_up.setObjectName("pushButton_jt_1_up")
        self.gridLayout.addWidget(self.pushButton_jt_1_up, 2, 2, 1, 1)
        self.pushButton_jt_2_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_2_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_2_down.setStyleSheet("background:#F76677;border-radius:5px;")
        self.pushButton_jt_2_down.setDefault(False)
        self.pushButton_jt_2_down.setObjectName("pushButton_jt_2_down")
        self.gridLayout.addWidget(self.pushButton_jt_2_down, 3, 0, 1, 1)
        self.lineEdit_jt_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_2.setObjectName("lineEdit_jt_2")
        self.gridLayout.addWidget(self.lineEdit_jt_2, 3, 1, 1, 1)
        self.lineEdit_jt_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_3.setObjectName("lineEdit_jt_3")
        self.gridLayout.addWidget(self.lineEdit_jt_3, 4, 1, 1, 1)
        self.lineEdit_jt_0 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_0.setObjectName("lineEdit_jt_0")
        self.gridLayout.addWidget(self.lineEdit_jt_0, 1, 1, 1, 1)
        self.pushButton_jt_b_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jt_b_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_jt_b_up.setMaximumSize(QtCore.QSize(22, 16777215))
        self.pushButton_jt_b_up.setToolTip("")
        self.pushButton_jt_b_up.setWhatsThis("")
        self.pushButton_jt_b_up.setStyleSheet("background:#6DDF6D;border-radius:5px;")
        self.pushButton_jt_b_up.setCheckable(False)
        self.pushButton_jt_b_up.setObjectName("pushButton_jt_b_up")
        self.gridLayout.addWidget(self.pushButton_jt_b_up, 0, 2, 1, 1)
        self.lineEdit_jt_b = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_jt_b.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_jt_b.setObjectName("lineEdit_jt_b")
        self.gridLayout.addWidget(self.lineEdit_jt_b, 0, 1, 1, 1)
        self.comboBox_finger = QtWidgets.QComboBox(Dialog)
        self.comboBox_finger.setGeometry(QtCore.QRect(35, 30, 79, 22))
        self.comboBox_finger.setStyleSheet("border:1pt solid gray")
        self.comboBox_finger.setObjectName("comboBox_finger")
        self.comboBox_finger.addItem("")
        self.comboBox_finger.addItem("")
        self.comboBox_finger.addItem("")
        self.comboBox_finger.addItem("")
        self.comboBox_finger.addItem("")
        self.lineEdit_delta_jtAngle = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_delta_jtAngle.setGeometry(QtCore.QRect(130, 30, 60, 22))
        self.lineEdit_delta_jtAngle.setStyleSheet("border:1px solid gray")
        self.lineEdit_delta_jtAngle.setObjectName("lineEdit_delta_jtAngle")

        self.retranslateUi(Dialog)
        self.pushButton_jt_b_up.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_0_up.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_1_up.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_2_up.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_3_up.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_b_down.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_0_down.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_1_down.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_2_down.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_jt_3_down.clicked.connect(Dialog.increase_jt_angle)
        self.pushButton_set.clicked.connect(Dialog.increase_jt_angle)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set joint angle"))
        self.pushButton_set.setText(_translate("Dialog", "Set"))
        self.lineEdit_jt_1.setPlaceholderText(_translate("Dialog", "0"))
        self.pushButton_jt_0_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_b_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_3_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_1_down.setText(_translate("Dialog", "-"))
        self.pushButton_jt_0_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_3_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_2_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_1_up.setText(_translate("Dialog", "+"))
        self.pushButton_jt_2_down.setText(_translate("Dialog", "-"))
        self.lineEdit_jt_2.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_jt_3.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_jt_0.setPlaceholderText(_translate("Dialog", "0"))
        self.pushButton_jt_b_up.setText(_translate("Dialog", "+"))
        self.lineEdit_jt_b.setPlaceholderText(_translate("Dialog", "0"))
        self.comboBox_finger.setItemText(0, _translate("Dialog", "Finger1"))
        self.comboBox_finger.setItemText(1, _translate("Dialog", "Finger2"))
        self.comboBox_finger.setItemText(2, _translate("Dialog", "Finger3"))
        self.comboBox_finger.setItemText(3, _translate("Dialog", "Finger4"))
        self.comboBox_finger.setItemText(4, _translate("Dialog", "Finger5"))
        self.lineEdit_delta_jtAngle.setPlaceholderText(_translate("Dialog", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

