# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/zhangqb/catkin_ws/src/gazebo_tutorials/scripts/hand_show/ui/robot_arm_joint.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(543, 196)
        Dialog.setStyleSheet("background:white")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_joint2_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint2_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint2_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint2_down.setDefault(False)
        self.pushButton_joint2_down.setObjectName("pushButton_joint2_down")
        self.gridLayout.addWidget(self.pushButton_joint2_down, 3, 3, 1, 1)
        self.pushButton_joint3_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint3_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint3_up.setToolTip("")
        self.pushButton_joint3_up.setWhatsThis("")
        self.pushButton_joint3_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint3_up.setCheckable(False)
        self.pushButton_joint3_up.setObjectName("pushButton_joint3_up")
        self.gridLayout.addWidget(self.pushButton_joint3_up, 1, 4, 1, 1)
        self.pushButton_joint1_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint1_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint1_up.setToolTip("")
        self.pushButton_joint1_up.setWhatsThis("")
        self.pushButton_joint1_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint1_up.setCheckable(False)
        self.pushButton_joint1_up.setObjectName("pushButton_joint1_up")
        self.gridLayout.addWidget(self.pushButton_joint1_up, 1, 2, 1, 1)
        self.lineEdit_joint3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint3.setObjectName("lineEdit_joint3")
        self.gridLayout.addWidget(self.lineEdit_joint3, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.pushButton_joint1_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint1_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint1_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint1_down.setDefault(False)
        self.pushButton_joint1_down.setObjectName("pushButton_joint1_down")
        self.gridLayout.addWidget(self.pushButton_joint1_down, 3, 2, 1, 1)
        self.pushButton_joint2_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint2_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint2_up.setToolTip("")
        self.pushButton_joint2_up.setWhatsThis("")
        self.pushButton_joint2_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint2_up.setCheckable(False)
        self.pushButton_joint2_up.setObjectName("pushButton_joint2_up")
        self.gridLayout.addWidget(self.pushButton_joint2_up, 1, 3, 1, 1)
        self.lineEdit_joint0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint0.setObjectName("lineEdit_joint0")
        self.gridLayout.addWidget(self.lineEdit_joint0, 2, 1, 1, 1)
        self.pushButton_joint0_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint0_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint0_up.setToolTip("")
        self.pushButton_joint0_up.setWhatsThis("")
        self.pushButton_joint0_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint0_up.setCheckable(False)
        self.pushButton_joint0_up.setObjectName("pushButton_joint0_up")
        self.gridLayout.addWidget(self.pushButton_joint0_up, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 2, 1)
        self.lineEdit_joint1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint1.setObjectName("lineEdit_joint1")
        self.gridLayout.addWidget(self.lineEdit_joint1, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.lineEdit_delta = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_delta.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_delta.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_delta.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delta.setObjectName("lineEdit_delta")
        self.gridLayout.addWidget(self.lineEdit_delta, 2, 0, 1, 1)
        self.lineEdit_joint2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint2.setObjectName("lineEdit_joint2")
        self.gridLayout.addWidget(self.lineEdit_joint2, 2, 3, 1, 1)
        self.pushButton_joint3_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint3_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint3_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint3_down.setDefault(False)
        self.pushButton_joint3_down.setObjectName("pushButton_joint3_down")
        self.gridLayout.addWidget(self.pushButton_joint3_down, 3, 4, 1, 1)
        self.pushButton_joint0_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint0_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint0_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint0_down.setDefault(False)
        self.pushButton_joint0_down.setObjectName("pushButton_joint0_down")
        self.gridLayout.addWidget(self.pushButton_joint0_down, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setStyleSheet("\n"
"font: 12pt \"Sans Serif\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 7, 1, 1)
        self.pushButton_joint4_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint4_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint4_up.setToolTip("")
        self.pushButton_joint4_up.setWhatsThis("")
        self.pushButton_joint4_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint4_up.setCheckable(False)
        self.pushButton_joint4_up.setObjectName("pushButton_joint4_up")
        self.gridLayout.addWidget(self.pushButton_joint4_up, 1, 5, 1, 1)
        self.pushButton_joint5_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint5_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint5_up.setToolTip("")
        self.pushButton_joint5_up.setWhatsThis("")
        self.pushButton_joint5_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint5_up.setCheckable(False)
        self.pushButton_joint5_up.setObjectName("pushButton_joint5_up")
        self.gridLayout.addWidget(self.pushButton_joint5_up, 1, 6, 1, 1)
        self.pushButton_joint6_up = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint6_up.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint6_up.setToolTip("")
        self.pushButton_joint6_up.setWhatsThis("")
        self.pushButton_joint6_up.setStyleSheet("QPushButton{background:#6DDF6D;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint6_up.setCheckable(False)
        self.pushButton_joint6_up.setObjectName("pushButton_joint6_up")
        self.gridLayout.addWidget(self.pushButton_joint6_up, 1, 7, 1, 1)
        self.pushButton_joint4_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint4_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint4_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint4_down.setDefault(False)
        self.pushButton_joint4_down.setObjectName("pushButton_joint4_down")
        self.gridLayout.addWidget(self.pushButton_joint4_down, 3, 5, 1, 1)
        self.pushButton_joint5_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint5_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint5_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint5_down.setDefault(False)
        self.pushButton_joint5_down.setObjectName("pushButton_joint5_down")
        self.gridLayout.addWidget(self.pushButton_joint5_down, 3, 6, 1, 1)
        self.pushButton_joint6_down = QtWidgets.QPushButton(Dialog)
        self.pushButton_joint6_down.setMinimumSize(QtCore.QSize(22, 22))
        self.pushButton_joint6_down.setStyleSheet("QPushButton{background:#F76677;border-radius:5px;}\n"
"QPushButton:hover{font-size:18px;}")
        self.pushButton_joint6_down.setDefault(False)
        self.pushButton_joint6_down.setObjectName("pushButton_joint6_down")
        self.gridLayout.addWidget(self.pushButton_joint6_down, 3, 7, 1, 1)
        self.lineEdit_joint4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint4.setObjectName("lineEdit_joint4")
        self.gridLayout.addWidget(self.lineEdit_joint4, 2, 5, 1, 1)
        self.lineEdit_joint5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint5.setObjectName("lineEdit_joint5")
        self.gridLayout.addWidget(self.lineEdit_joint5, 2, 6, 1, 1)
        self.lineEdit_joint6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_joint6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_joint6.setObjectName("lineEdit_joint6")
        self.gridLayout.addWidget(self.lineEdit_joint6, 2, 7, 1, 1)
        self.pushButton_set_all_angle = QtWidgets.QPushButton(Dialog)
        self.pushButton_set_all_angle.setObjectName("pushButton_set_all_angle")
        self.gridLayout.addWidget(self.pushButton_set_all_angle, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_joint0_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint1_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint2_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint3_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint4_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint5_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint6_up.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint0_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint1_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint2_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint3_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint4_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint5_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_joint6_down.clicked.connect(Dialog.increase_joint_angle)
        self.pushButton_set_all_angle.clicked.connect(Dialog.set_all_angle)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Set Arm Joint"))
        self.pushButton_joint2_down.setText(_translate("Dialog", "-"))
        self.pushButton_joint3_up.setText(_translate("Dialog", "+"))
        self.pushButton_joint1_up.setText(_translate("Dialog", "+"))
        self.lineEdit_joint3.setPlaceholderText(_translate("Dialog", "None"))
        self.label_7.setText(_translate("Dialog", "Joint 3"))
        self.pushButton_joint1_down.setText(_translate("Dialog", "-"))
        self.pushButton_joint2_up.setText(_translate("Dialog", "+"))
        self.lineEdit_joint0.setPlaceholderText(_translate("Dialog", "None"))
        self.pushButton_joint0_up.setText(_translate("Dialog", "+"))
        self.pushButton_3.setText(_translate("Dialog", "Delta"))
        self.lineEdit_joint1.setPlaceholderText(_translate("Dialog", "None"))
        self.label_5.setText(_translate("Dialog", "Joint 1"))
        self.lineEdit_delta.setPlaceholderText(_translate("Dialog", "0"))
        self.lineEdit_joint2.setPlaceholderText(_translate("Dialog", "None"))
        self.pushButton_joint3_down.setText(_translate("Dialog", "-"))
        self.pushButton_joint0_down.setText(_translate("Dialog", "-"))
        self.label_6.setText(_translate("Dialog", "Joint 2"))
        self.label_4.setText(_translate("Dialog", "Joint 0"))
        self.label_8.setText(_translate("Dialog", "Joint 4"))
        self.label_10.setText(_translate("Dialog", "Joint 5"))
        self.label_9.setText(_translate("Dialog", "Joint 6"))
        self.pushButton_joint4_up.setText(_translate("Dialog", "+"))
        self.pushButton_joint5_up.setText(_translate("Dialog", "+"))
        self.pushButton_joint6_up.setText(_translate("Dialog", "+"))
        self.pushButton_joint4_down.setText(_translate("Dialog", "-"))
        self.pushButton_joint5_down.setText(_translate("Dialog", "-"))
        self.pushButton_joint6_down.setText(_translate("Dialog", "-"))
        self.lineEdit_joint4.setPlaceholderText(_translate("Dialog", "None"))
        self.lineEdit_joint5.setPlaceholderText(_translate("Dialog", "None"))
        self.lineEdit_joint6.setPlaceholderText(_translate("Dialog", "None"))
        self.pushButton_set_all_angle.setText(_translate("Dialog", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

